jobmanager:
  heap.size: 96g
  rpc.address: flink-jobmanager
  rpc.port: 6123

taskmanager:
  heap.size: 384g
  numberOfTaskSlots: 48
  memory:
    process.size: 480g
    framework.heap.size: 128g
    task.heap.size: 256g
    managed.size: 64g
    network.memory.min: 64g
    network.memory.max: 64g

parallelism:
  default: 384

restart-strategy:
  type: failure-rate
  max-failures-per-interval: 3
  failure-rate-interval: 5min
  delay: 10s